name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      uses: docker/build-push-action@v4.0.0
      with:
        context:
        file: Dockerfile
        push : true
        tag: $DOCKER_USERNAME/newimage:latest
    
    - name : docker login
      env:
        DOCKER_USERNAME : ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD : ${{ secrets. DOCKERHUB_PASSWORD }}
      run : |
        docker login -u $DOCKER_USERNAME -p $DOCKERHUB_PASSWORD
        
    - name : Docker push to docker hub
      run: docker push $DOCKER_USERNAME/frontend
    
       
