name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      uses: docker/setup-buildx-action@v2.5.0
      with:
        context:
        file: Dockerfile
        push : true
        tag: frontend/name:latest
    
    - name : docker login
      env:
        DOCKER_USERNAME : ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD : ${{ secrets. DOCKERHUB_PASSWORD }}
      run : |
        docker login -u $DOCKER_USERNAME -p $DOCKERHUB_PASSWORD
        
    - name : Docker push to docker hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nadeem-sleep
    
       
